language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"

install: "python -m pip install --upgrade pip && pip install requests && pip install scipy && pip install numpy && pip install sklearn && pip install pandas"

script: py.test